version: '3.9'
name: conv_video
services:
  conv:
    container_name: 'conv_video'
    image: zhangyiming748/convertvideo:latest
    volumes:
      - '/path/to/video:/data'
    deploy:
      resources:
        limits:
          memory: 8192M
          cpus: '4'
    environment:
      - root=/data
      - to=h265
      - direction=ToRight
      - trans = 0 # 0不翻译标题